# --- Configuration --- #

show-sethome-message: true
sethome-message: '&2[&a*&2]&a &aYou now have a new home, &6%player%&a!'

show-teleport-message: false
teleport-message: '&2[&a*&2]&a &aYou have been teleported to your home, &6%player%&a!'

play-warp-sound: true
respawn-player-at-home: true

# previous name: sethome-time-delay
# set this to 0 to disabled delay
sethome-delay-seconds: 5

# previous name: home-time-delay
# set this to 0 to disabled delay
home-delay-seconds: 5
home-warmup-instead-of-cooldown: false