main: me.downthepark.sethome.SetHome
name: SetHome
version: 6.1.1
api-version: 1.16
description: A lightweight SetHome plugin for Bukkit/Spigot
commands:
  sethome:
    description: Set your home
  home:
    description: Warp to your home